# Basic Settings
set -g mouse on
set -g history-limit 10000
setw -g mode-keys vi
set -g set-clipboard on

# Appearance
set -g status-style bg=#0d0d0d,fg=white

# Copy Mode Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# --- RESTORE & CONTINUUM ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# 1. Resurrect: Manually save/restore
set -g @plugin 'tmux-plugins/tmux-resurrect'

# 2. Continuum: Auto save/restore
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'off'  # Auto-restore on startup

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# --- COLORS  ---
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"


